name: nightly docker builds

on:
  # to trigger manually if we really need it
  workflow_dispatch:

  push:
    branches:
      - 'main'

  schedule:
    # * is a special character in YAML so you have to quote this string
    # triggers every day at 00:00 UTC (midnight)
    - cron: '0 0 * * *'

jobs:
  docker-amd64:
    environment: 'docker-amd64'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          repository: 'techlgbt/techlgbt'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build/push
        uses: docker/build-push-action@v6
        with:
          push: true
          # build from docker/ directory
          context: .
          platforms: linux/amd64
          tags: |
            jessebot/mastodon-lgbt-glitch:latest

  docker-arm64:
    environment: 'docker-arm64'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'techlgbt/techlgbt'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build/push - arm
        uses: docker/build-push-action@v6
        with:
          push: true
          # build from docker/ directory
          context: .
          platforms: linux/arm64
          tags: |
            jessebot/mastodon-lgbt-glitch:latest
