name: nightly docker builds

on:
  # to trigger manually if we really need it
  workflow_dispatch:

  push:
    branches:
      - 'main'

  schedule:
    # * is a special character in YAML so you have to quote this string
    # triggers every day at 00:00 UTC (midnight)
    - cron: '0 0 * * *'

jobs:
  docker-amd64:
    environment: 'docker-amd64'
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
        name: Checkout glitch-soc/mastodon repo
        with:
          # Repository name with owner. For example, actions/checkout
          repository: 'glitch-soc/mastodon'

      - id: glitchsoc
        name: Get latest glitch-soc release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: glitch-soc
          repo: mastodon
          excludes: prerelease, draft

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build/push
        uses: docker/build-push-action@v6
        with:
          push: true
          # build from docker/ directory
          context: .
          platforms: linux/amd64
          tags: |
            jessebot/mastodon-glitch-soc:latest
            jessebot/mastodon-glitch-soc:${{ steps.glitchsoc.outputs.release }}
